### ISSUE TITLE
Issue when sending emails with attachments in 1.0.6

### ISSUE THREAD

**Issue by mikerogerz** [narendravaghela/cakephp-mailgun#12] opened 2018-06-27 22:54 UTC
```
Warning Error: fopen() expects parameter 1 to be a valid path, array given in [/home/mrogers/Dropbox/cakephp/webapp/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php, line 310]

2018-06-27 22:40:15 Warning: Warning (2): fopen() expects parameter 1 to be a valid path, array given in [/home/mrogers/Dropbox/cakephp/webapp/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php, line 310]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 153
fopen - [internal], line ??
Mailgun\Connection\RestClient::prepareFile() - ROOT/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php, line 310
Mailgun\Connection\RestClient::post() - ROOT/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php, line 154
Mailgun\Mailgun::post() - ROOT/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php, line 204
Mailgun\Mailgun::sendMessage() - ROOT/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php, line 135
MailgunEmail\Mailer\Transport\MailgunTransport::_sendMessage() - ROOT/vendor/narendravaghela/cakephp-mailgun/src/Mailer/Transport/MailgunTransport.php, line 216
App\Mailer\Transport\MailgunTransport::send() - APP/Mailer/Transport/MailgunTransport.php, line 95
Cake\Mailer\Email::send() - CORE/src/Mailer/Email.php, line 2118
EmailQueue\Shell\SenderShell::main() - ROOT/plugins/EmailQueue/src/Shell/SenderShell.php, line 106
Cake\Console\Shell::runCommand() - CORE/src/Console/Shell.php, line 507
Cake\Console\CommandRunner::run() - CORE/src/Console/CommandRunner.php, line 141
[main] - ROOT/bin/cake.php, line 12
```
No issues with 1.0.5.

**Comment by narendravaghela** [comment] 2018-06-28 05:36
Hi @mikerogerz 
Thanks for reporting the issue, the latest release might have an issue due to inline attachment functionality.
I will check it out and fix asap. You can continue using 1.0.5 version for now.

**Comment by narendravaghela** [comment] 2018-06-28 06:22
It works well on my new setup. Can you please provide the steps to reproduce this error?

**Comment by narendravaghela** [comment] 2018-07-05 06:07
Hi @mikerogerz 

Is it working for you? Let me know, so I can close this issue.

**Comment by mikerogerz** [comment] 2018-07-05 15:32
I haven't had a chance to properly debug yet, but I'll be able to get to it
this weekend. It's definitely still happening, without changing anything in
my code except for updating the plugin.

**Comment by narendravaghela** [comment] 2018-10-08 07:51
Please reopen if you still face the issue. I suggest to upgrade to latest `3.0.0`.

**Closed as completed by narendravaghela** 2018-10-08 07:51 UTC
